version: '3.8'
services:

  # Application & web server
  app:
    container_name: task-app
    build:
      context: .
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      - "database"
    ports:
      - 8081:80
    networks:
      - task-app-network
  # Database
  database:
    container_name: task-app-database
    image: mysql:5.7-debian
    volumes:
      - task-app-db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: app
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: admin
      MYSQL_USER: admin
    ports:
      - "33062:3306"
    networks:
      - task-app-network
  # Database management
  pma:
    container_name: task-app-pma
    image: phpmyadmin:5.1
    networks:
      - task-app-network
    environment:
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - database
    ports:
      - 8888:80

volumes:
  task-app-db-data:

networks:
  task-app-network: